#!/bin/bash
# This script took inspiration from the Pi-Hole and RaspAP installer script.
# Created with love by QinCai with assistance from Copilot
# ASCII art generated by https://patorjk.com/software/taag/
# MAKE SURE THAT YOU HAVE DOWNLOADED THIS SCRIPT FROM A TRUST-WORTHY SOURCE!!!

set -e

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
MAGENTA='\033[1;35m'
CYAN='\033[1;36m'
NC='\033[0m' # No Color

AUTO_CONFIRM=false

confirm() {
    if [ "$AUTO_CONFIRM" = true ]; then
        return 0
    fi

    read -r -p "$1 [y/n]: " yn
    case $yn in
        [Yy]* ) return 0;;
        [Nn]* ) echo -e "${RED}Installation aborted.${NC}"; exit 1;;
        * ) echo -e "${YELLOW}Please answer yes or no.${NC}";;
    esac
}

if [ "$1" = "-y" ]; then
    AUTO_CONFIRM=true
fi

log_success() {
    echo -e "${GREEN}[✔] $1${NC}"
}

log_failure() {
    echo -e "${RED}[✘] $1${NC}"
}

log_info() {
    echo -e "${BLUE}[ℹ] $1${NC}"
}

log_warning() {
    echo -e "${MAGENTA}[⚠] $1${NC}"
}

check_root() {
    log_info "Checking for root privileges..."
    if [ "$EUID" -ne 0 ]; then
        log_failure "Please run as root."
        exit 1
    else
        log_success "Running as root."
    fi
}

check_rpi() {
    log_info "Checking if running on a Raspberry Pi..."
    if grep -q "Raspberry Pi" /proc/cpuinfo; then
        log_success "Running on a Raspberry Pi."
    else
        log_failure "This script can only be run on a Raspberry Pi."
        exit 1
    fi
}

check_curl() {
    log_info "Checking for curl..."
    if ! command -v curl &> /dev/null; then
        log_failure "curl could not be found."
        confirm "Install curl?"
        sudo apt-get update && sudo apt-get install -y curl
        log_success "curl installed!"
    else
        log_success "curl is already installed."
    fi
}

check_vcgencmd() {
    log_info "Checking installation of vcgencmd..."
    if ! command -v vcgencmd &> /dev/null; then
        log_failure "vcgencmd could not be found."
        confirm "Install vcgencmd and other packages?"

        log_info "Installing compilers..."
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
        log_success "Compilers installed."

        log_info "Downloading Userland..."
        cd /tmp
        git clone https://github.com/raspberrypi/userland.git
        cd userland
        log_success "Downloaded Userland."

        log_info "Building from source... This might take a while."
        ./buildme --aarch64
        log_success "Build complete!"

        log_info "Performing some housekeeping..."
        sudo mv build/host_applications/linux/apps/gencmd/gencmd /usr/local/bin/vcgencmd
        sudo chown root:video /usr/local/bin/vcgencmd
        sudo chmod 775 /usr/local/bin/vcgencmd
        sudo mv build/lib/libvchiq_arm.so build/lib/libvcos.so /lib/
        log_success "Housekeeping done."

        read -r -p "Enter the username to add to the video group (your username): " username
        if id "$username" &>/dev/null; then
            log_info "Adding users to the video group..."
            sudo usermod -aG video "$username"
            sudo usermod -aG video root
            log_success "Users added to the video group."
        else
            log_failure "User $username does not exist."
            exit 1
        fi

        log_info "Setting up udev rules..."
        echo 'SUBSYSTEM=="vchiq", GROUP="video", MODE="0660"' | sudo tee /etc/udev/rules.d/99-input.rules
        sudo udevadm control --reload-rules && sudo udevadm trigger
        log_success "Udev rules set up."
        if ! command -v vcgencmd &> /dev/null; then
            log_failure "FATAL: vcgencmd not found!!!"
        else
            log_success "vcgencmd installed!"
        fi
    else
        log_success "vcgencmd is already installed."
    fi
}

main() {
    clear
    echo "Welcome to the RPi Metrics installation script!"
    sleep 1
    echo -e "${CYAN}  _____   _____  _   __  __        _          _            "
    echo -e "${CYAN} |  __ \ |  __ \(_) |  \/  |      | |        (_)           "
    echo -e "${CYAN} | |__) || |__) |_  | \  / |  ___ | |_  _ __  _   ___  ___ "
    echo -e "${CYAN} |  _  / |  ___/| | | |\/| | / _ \| __|| '__|| | / __|/ __|"
    echo -e "${CYAN} | | \ \ | |    | | | |  | ||  __/| |_ | |   | || (__ \__ \\"
    echo -e "${CYAN} |_|  \_\|_|    |_| |_|  |_| \___| \__||_|   |_| \___||___/"
    echo ""
    sleep 1
    echo -e "${NC}Make sure that you have downloaded this script from a trustworthy source!!"
    echo ""
    sleep 1
    echo -e "${BLUE}#########################################################"
    echo "#                   Not working??                       #"
    echo "#                                                       #"
    echo "#  Try running these, one after another:                #"
    echo "#   \$ wget https://qincai.xyz/rpi-metrics-installer.sh  #"
    echo "#   \$ chmod +x rpi-metrics-installer.sh                 #"
    echo "#   \$ sudo ./rpi-metrics-installer.sh                   #"
    echo "#########################################################"
    echo ""
    sleep 2

    check_root
    sleep 1

    check_rpi
    sleep 1

    check_curl
    sleep 1

    confirm "Update your package list and install necessary packages?"

    log_info "Updating package list and installing necessary packages..."
    # Update package list and install necessary packages
    if sudo apt-get update && sudo apt-get install -y python3 python3-pip python3-venv; then
        log_success "Package list updated and necessary packages installed."
    else
        log_failure "Failed to update package list or install necessary packages."
    fi

    check_vcgencmd

    confirm "Create a directory for rpi-metrics in /usr/share?"

    log_info "Creating directory for rpi-metrics..."
    # Create a directory for rpi-metrics
    if sudo mkdir -p /usr/share/rpi-metrics && cd /usr/share/rpi-metrics; then
        log_success "Directory for rpi-metrics created in /usr/share."
    else
        log_failure "Failed to create directory for rpi-metrics."
        exit 1
    fi

    confirm "Clone the RPi-Metrics repository?"

    log_info "Cloning the RPi-Metrics repository..."
    # Clone the repository
    if git -c http.followRedirects=true clone https://github.com/QinCai-rui/RPi-Metrics.git /usr/share/rpi-metrics; then
        log_success "RPi-Metrics server repository cloned successfully."
    else
        log_failure "Failed to clone RPi-Metrics server repository."
        exit 1
    fi

    log_info "Setting up the Flask application..."
    cd /usr/share/rpi-metrics/Server
    sudo python3 -m venv venv
    source venv/bin/activate
    sudo venv/bin/pip install Flask
    deactivate
    log_success "Flask application set up successfully."

    confirm "Copy the systemd service file?"

    log_info "Copying the systemd service file..."
    # Copy the systemd service file
    if sudo cp /usr/share/rpi-metrics/Server/rpi-metricsd.service /etc/systemd/system/; then
        log_success "Systemd service file copied successfully."
    else
        log_failure "Failed to copy systemd service file."
        exit 1
    fi

    log_info "Reloading systemd daemon..."
    # Reload systemd daemon
    if sudo systemctl daemon-reload; then
        log_success "Systemd daemon reloaded."
    else
        log_failure "Failed to reload systemd daemon."
    fi

    confirm "Start and enable the rpi-metricsd service?"

    log_info "Starting and enabling the rpi-metricsd service..."
    # Start and enable the rpi-metricsd service
    if sudo systemctl start rpi-metricsd && sudo systemctl enable rpi-metricsd; then
        log_success "rpi-metricsd service started and enabled."
    else
        log_failure "Failed to start or enable rpi-metricsd service."
        exit 1
    fi

    echo -e "${GREEN}RPi Metrics installation completed!${NC}"
}


main "$@"
